version: '3'
services: 
  mongoDb:
   image: 'mongo'
   port:
    - 27017:27107
   environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
  
  mongo-express:
   image: 'mongo-express'
   port:
    - 8081:8081
   environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
   - ME_CONFIG_MONGODB_ADMINPASSWORD=admin 
   - ME_CONFIG_MONGODB_SERVER=mongoDB 
   - ME_CONFIG_BASICAUTH_USERNAME=admin 
   - ME_CONFIG_BASICAUTH_PASSWORD=admin